export default function Sources() {
    return (
    <div>
        <h1>WORD FIGHT</h1>
        <h2>Sources</h2>
        <div className="list-bg">
        <h3>Graphics: </h3>
        <ul>
        <li>Monsters in background image generated by <a href="https://pixelencounter.com/Api">Pixel Encounter</a>.</li>
        <li>Others created by Monxque.</li>
        </ul>
        <h3>Fonts and Text: </h3>
        <ul>
        <li>Google Fonts <a href="https://fonts.google.com/specimen/Press+Start+2P">Press Start 2P</a> and <a href="https://fonts.google.com/specimen/VT323">VT323</a> are used.</li>
        <li>Text contents are created by Monxque.</li>
        </ul>

      
        </div>
    </div>
    );
}
