export default function Sources() {
    return (
    <div>
        <h1>WORD FIGHT</h1>
        <h2>Sources</h2>
        <div className="list-bg">
        <h3>Graphics: </h3>
        <ul>
        <li>Monsters in background picture generated by <a href="https://pixelencounter.com/Api">Pixel Encounter</a>.</li>
        <li>Others created by Monxque.</li>
        </ul>

        <h3>Third Party API:</h3>
        <ul>
            <li>Monsters from <a href="https://pixelencounter.com/Api">Pixel Encounter</a></li>
            <li>Words from <a href="http://metaphorpsum.com/">Metaphorpsum</a></li>
        </ul>
        </div>
    </div>
    );
}
